// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.qidi.grpcsdk.idl;

public interface HelloListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.HelloListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string name = 1;</code>
   * @return A list containing the name.
   */
  java.util.List<java.lang.String>
      getNameList();
  /**
   * <code>repeated string name = 1;</code>
   * @return The count of name.
   */
  int getNameCount();
  /**
   * <code>repeated string name = 1;</code>
   * @param index The index of the element to return.
   * @return The name at the given index.
   */
  java.lang.String getName(int index);
  /**
   * <code>repeated string name = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the name at the given index.
   */
  com.google.protobuf.ByteString
      getNameBytes(int index);
}
