// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.qidi.grpcsdk.idl;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   * @return The result.
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
