// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.qidi.grpcsdk.idl;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_HelloResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_HelloListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_HelloListRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\007message\"\034\n\014HelloRequest" +
      "\022\014\n\004name\030\001 \001(\t\"\037\n\rHelloResponse\022\016\n\006resul" +
      "t\030\001 \001(\t\" \n\020HelloListRequest\022\014\n\004name\030\001 \003(" +
      "\t2\344\002\n\016MessageService\0228\n\005hello\022\025.message." +
      "HelloRequest\032\026.message.HelloResponse\"\000\022F" +
      "\n\021helloServerStream\022\025.message.HelloReque" +
      "st\032\026.message.HelloResponse\"\0000\001\022F\n\021helloC" +
      "lientStream\022\025.message.HelloRequest\032\026.mes" +
      "sage.HelloResponse\"\000(\001\022F\n\017helloBidiStrea" +
      "m\022\025.message.HelloRequest\032\026.message.Hello" +
      "Response\"\000(\0010\001\022@\n\thelloList\022\031.message.He" +
      "lloListRequest\032\026.message.HelloResponse\"\000" +
      "B&\n\024com.qidi.grpcsdk.idlB\014MessageProtoP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_message_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_message_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_message_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_HelloResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_message_HelloListRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_message_HelloListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_HelloListRequest_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
